version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    networks:
      - airflow_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - airflow_network

  airflow-webserver:
    build: .  # This will build the image using the Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8080:8080"
    networks:
      - airflow_network
    depends_on:
      - postgres
      - redis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./output:/opt/airflow/output  # Mount a local directory for output
    command: >
      bash -c "
        airflow db init && 
        airflow webserver
      "

  airflow-scheduler:
    build: .  # This will build the image using the Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
    networks:
      - airflow_network
    depends_on:
      - postgres
      - redis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./output:/opt/airflow/output  # Mount a local directory for output
    command: >
      bash -c "
        airflow db init && 
        airflow scheduler
      "

  airflow-worker:
    build: .  # This will build the image using the Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=redis://redis:6379/0
    networks:
      - airflow_network
    depends_on:
      - postgres
      - redis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./output:/opt/airflow/output  # Mount a local directory for output
    command: ["airflow", "worker"]

networks:
  airflow_network:
    driver: bridge
