version: '3.7'

services:
  airflow:
    build:
      context: ./ 
      dockerfile: Dockerfile
    image: airflowimage
    container_name: cars24_etl_pipeline
    ports:
      - "8080:8080"      # Expose Airflow Web UI
    environment:
      - AIRFLOW_ENV=production
      - AIRFLOW_HOME=/app/airflow
    networks:
      - my_network
    volumes:
      - "./dags:/app/airflow/dags"
      - "./scripts:/app/scripts"
      - "./output:/app/output"
      - "./logs:/app/airflow/logs"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - my_network
    ports:
      - "6379:6379"

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: